# Generated by Django 4.2.5 on 2023-09-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='stop_updated_price',
            new_name='update_prices',
        ),
    ]
