# Generated by Django 4.2.5 on 2023-10-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_stop_updated_price_shop_update_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='individual_updating_time',
        ),
    ]
