# Generated by Django 4.2.5 on 2023-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_individual_updating_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='shop',
            table='shops',
        ),
    ]
