# Generated by Django 4.2.5 on 2023-10-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_options_alter_shop_name_alter_shop_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='api_key',
            new_name='ozon_api_key',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='update_prices',
            new_name='price_updating',
        ),
        migrations.AlterField(
            model_name='shop',
            name='client_id',
            field=models.CharField(max_length=8, verbose_name='Client-Id Ozon'),
        ),
    ]
