# Generated by Django 4.2.5 on 2023-10-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_api_key_shop_ozon_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shipper_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Api-Key поставщика'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Магазин активен'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ozon_api_key',
            field=models.CharField(max_length=50, verbose_name='Api-Key Ozon'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_updating',
            field=models.BooleanField(default=True, verbose_name='Обновление цен'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='vendor_name',
            field=models.CharField(default='Сималенд', max_length=50, verbose_name='Поставщик'),
        ),
    ]
