# Generated by Django 4.2.5 on 2023-10-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_shipper_api_key_alter_shop_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='Warehouse',
        ),
    ]
