# Generated by Django 4.2.5 on 2023-10-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_storage_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='ozon_id',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_id',
            field=models.PositiveBigIntegerField(default=12345, verbose_name='id Склада'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='shop.shop', verbose_name='Магазин'),
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='warehouses',
        ),
    ]
