# Generated by Django 4.2.5 on 2023-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('AD', 'admin'), ('SE', 'seller')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_logged_out', models.BooleanField(default=True)),
                ('shops', models.ManyToManyField(blank=True, to='shop.shop')),
            ],
            options={
                'verbose_name': 'telegram user',
                'verbose_name_plural': 'telegram users',
            },
        ),
    ]
