# Generated by Django 4.2.5 on 2023-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_logged_out',
            field=models.BooleanField(default=False),
        ),
    ]
